### ISSUE TITLE
See activities in my neighborhood

### ISSUE THREAD

**Issue by jonatassalgado** [jonatassalgado/villeme#4]
# Tasks
- [x] Add section in newsfeed.
- [x] Add events snippet.
- [x] Create route to activities in neighborhood.
# Acceptance Criteria
- [x] When User click to see all events of neighborhood then page does show all events in grids and remove the snippet.
